---
# tasks file for dockerce.install
- name: install required package to setup docker ce repository
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2

- name: setup docker ce repository
  yum_repository:
    name: docker-ce-stable
    description: Docker CE Stable
    baseurl: "{{dockerce_repository.baseurl}}"
    enabled: yes
    gpgcheck: yes
    gpgkey: "{{dockerce_repository.gpgkey}}"

- name: install docker ce
  yum:
    name: "docker-ce{{ '-' if ( dockerceVersion is  defined ) else ''}}{{dockerceVersion|default('')}}"
    state: present

- block:
    - file:
        path: /etc/systemd/system/docker.service.d
        state: directory
    - name: configure docker http proxy
      template:
        src: http-proxy.conf.j2
        dest: /etc/systemd/system/docker.service.d/http-proxy.conf
      notify: restart docker
  when: dockerce_http_proxy is defined


- name: start docker service
  service:
    name: docker
    state: started
    enabled: yes
